Repository aragon/govern, pull requests merged in 2020-10, with the labels that each got.

#52 📦 NEW: generate abi files using buidler-extract
  packages/erc3kjs/src/lib/abi/ERC3000Registry.json
  packages/erc3kjs/src/lib/abi/Eaglet.json
  packages/erc3kjs/src/lib/abi/EagletFactory.json
  packages/erc3kjs/src/lib/abi/OptimisticQueueFactory.json
  packages/govern-core/abi/DepositLib.json
  packages/govern-core/abi/ERC165.json
  packages/govern-core/abi/ERC20.json
  packages/govern-core/abi/ERC3000.json
  packages/govern-core/abi/ERC3000Data.json
  packages/govern-core/abi/ERC3000Executor.json
  packages/govern-core/abi/ERC3000Registry.json
  packages/govern-core/abi/Govern.json
  packages/govern-core/abi/GovernFactory.json
  packages/govern-core/abi/IArbitrable.json
  packages/govern-core/abi/IArbitrator.json
  packages/govern-core/abi/IERC3000.json
  packages/govern-core/abi/IERC3000Executor.json
  packages/govern-core/abi/MiniACL.json
  packages/govern-core/abi/MiniACLData.json
  packages/govern-core/abi/OptimisticQueue.json
  packages/govern-core/abi/OptimisticQueueFactory.json
  packages/govern-core/abi/OptimisticQueueStateLib.json
  packages/govern-core/abi/SafeERC20.json
  packages/govern-core/contracts/ERC3000Registry.sol
  packages/govern-core/package.json
  packages/govern-core/scripts/sync-abis.js
  yarn.lock
Labels: S7: Meta 🧛‍♀️, T2: DX 👷‍♀️

#63 govern-subgraph: Update subgraph readme
  packages/govern-subgraph/README.md
Labels: P3 🏖, S6: Docs 👩‍💻, T2: DX 👷‍♀️

#59 Server: add wrapper to fetch data from the graph
  packages/govern-server/package.json
  packages/govern-server/src/core/data/TheGraphWrapper.ts
  packages/govern-server/src/core/data/index.ts
  packages/govern-server/src/core/data/queries/fragments.ts
  packages/govern-server/src/core/data/queries/index.ts
  packages/govern-server/src/core/errors.ts
  packages/govern-server/src/core/params.ts
  packages/govern-server/src/core/types.ts
  packages/govern-server/src/core/utils/index.ts
  packages/govern-server/src/core/utils/network.ts
  yarn.lock
Labels: S1: Feature 👨‍🎨

#66 Add @aragon/govern-create package
  .github/workflows/cd-rinkeby.yml
  package.json
  packages/erc3k/contracts/IERC3000.sol
  packages/erc3k/scripts/sample-script.js
  packages/govern-contract-utils/test/acl.sol
  packages/govern-core/buidler.config.js
  packages/govern-create/.gitattributes
  packages/govern-create/.gitignore
  packages/govern-create/README.md
  packages/govern-create/buidler.config.js
  packages/govern-create/contracts/GovernBaseFactory.sol
  packages/govern-create/package.json
  packages/govern-create/test/base.js
  packages/govern-discord/package.json
  packages/govern-subgraph/manifest/data/mainnet-staging.json
  packages/govern-subgraph/manifest/data/mainnet.json
  packages/govern-subgraph/schema.graphql
  packages/govern-subgraph/src/GovernQueue.ts
  packages/govern-subgraph/subgraph.template.yaml
  yarn.lock
Labels: P2 👀, S7: Meta 🧛‍♀️, T0: Core 🌞, T2: DX 👷‍♀️

#68 core: optionality for allowing failures and add execution memo
  packages/erc3k/contracts/ERC3000Data.sol
  packages/erc3k/contracts/ERC3000Registry.sol
  packages/erc3k/contracts/IERC3000.sol
  packages/erc3k/contracts/IERC3000Executor.sol
  packages/erc3k/contracts/test/ERC3000ExecutorMock.sol
  packages/erc3k/contracts/test/ERC3000Mock.sol
  packages/govern-contract-utils/contracts/bitmaps/BitmapLib.sol
  packages/govern-contract-utils/contracts/test/BitmapLibMock.sol
  packages/govern-contract-utils/test/bitmaplib.js
  packages/govern-core/contracts/Govern.sol
  packages/govern-core/contracts/pipelines/GovernQueue.sol
  packages/govern-core/scripts/sync-abis.js
  packages/govern-core/test/govern.js
  packages/govern-core/test/pipelines/govern-queue.js
  packages/govern-create/scripts/sample-script.js
  packages/govern-subgraph/schema.graphql
  packages/govern-subgraph/subgraph.template.yaml
  yarn-error.log
Labels: P1 🔜, S1: Feature 👨‍🎨, T0: Core 🌞, T2: DX 👷‍♀️

#83 core: fix infinite loop on overflow in Govern.exec
  packages/govern-core/contracts/Govern.sol
Labels: P0 🚒, S2: Bug 👩‍✈️, T0: Core 🌞

#87 Core, utils: Implement adaptative ERC165
  packages/erc3k/contracts/ERC3000.sol
  packages/erc3k/contracts/ERC3000Data.sol
  packages/erc3k/contracts/ERC3000Executor.sol
  packages/erc3k/contracts/ERC3000Registry.sol
  packages/erc3k/contracts/IERC3000.sol
  packages/erc3k/contracts/IERC3000Executor.sol
  packages/erc3k/package.json
  packages/erc3k/test/erc3k-exec.test.ts
  packages/erc3k/test/erc3k.test.ts
  packages/govern-console/src/lib/abi/Govern.json
  packages/govern-console/src/lib/abi/GovernQueue.json
  packages/govern-contract-utils/contracts/adaptative-erc165/AdaptativeERC165.sol
  packages/govern-contract-utils/contracts/erc165/ERC165.sol
  packages/govern-core/contracts/Govern.sol
  packages/govern-core/contracts/pipelines/GovernQueue.sol
  packages/govern-core/test/govern.test.ts
  packages/govern-core/test/pipelines/govern-queue.test.ts
Labels: P1 🔜, S1: Feature 👨‍🎨, T0: Core 🌞

#89 ERC3k: hash missing payload fields
  packages/erc3k/contracts/ERC3000Data.sol
Labels: P0 🚒, S2: Bug 👩‍✈️, T0: Core 🌞

#88 Core, create, utils: Proxies in Factory
  .github/workflows/cd-rinkeby.yml
  packages/erc3k/contracts/ERC3000.sol
  packages/erc3k/contracts/ERC3000Registry.sol
  packages/govern-contract-utils/contracts/acl/ACL.sol
  packages/govern-contract-utils/contracts/address-utils/AddressUtils.sol
  packages/govern-contract-utils/contracts/initializable/Initializable.sol
  packages/govern-contract-utils/contracts/minimal-proxies/ERC1167ProxyFactory.sol
  packages/govern-core/contracts/Govern.sol
  packages/govern-core/contracts/pipelines/GovernQueue.sol
  packages/govern-create/buidler.config.js
  packages/govern-create/contracts/GovernBaseFactory.sol
  packages/govern-create/contracts/core-factories/GovernFactory.sol
  packages/govern-create/contracts/core-factories/GovernQueueFactory.sol
  packages/govern-create/tasks/deploy-factory.js
  packages/govern-create/tasks/deploy-govern.js
  packages/govern-create/test/base.js
  packages/govern-subgraph/manifest/data/rinkeby.json
Labels: P1 🔜, S1: Feature 👨‍🎨, T0: Core 🌞, T2: DX 👷‍♀️

#71 Server: add pending review changes
  packages/govern-server/src/core/GovernCore.ts
  packages/govern-server/src/core/GraphqlClient.ts
  packages/govern-server/src/core/config.ts
  packages/govern-server/src/core/errors.ts
  packages/govern-server/src/core/params.ts
  packages/govern-server/src/core/types.ts
  packages/govern-server/src/core/utils/network.ts
Labels: P2 👀, S1: Feature 👨‍🎨, T2: DX 👷‍♀️

#98 Core, erc3k: Remove veto collateral
  .github/workflows/cd-rinkeby.yml
  README.md
  packages/erc3k/contracts/ERC3000.sol
  packages/erc3k/contracts/ERC3000Data.sol
  packages/erc3k/contracts/ERC3000Executor.sol
  packages/erc3k/contracts/ERC3000Registry.sol
  packages/erc3k/contracts/IERC3000.sol
  packages/erc3k/contracts/IERC3000Executor.sol
  packages/erc3k/contracts/test/ERC3000Mock.sol
  packages/erc3k/package.json
  packages/erc3k/test/erc3k-exec.test.ts
  packages/erc3k/test/erc3k.test.ts
  packages/govern-console/src/lib/abi/Govern.json
  packages/govern-console/src/lib/abi/GovernQueue.json
  packages/govern-contract-utils/buidler.config.js
  packages/govern-contract-utils/contracts/acl/ACL.sol
  packages/govern-contract-utils/contracts/adaptative-erc165/AdaptativeERC165.sol
  packages/govern-contract-utils/contracts/address-utils/AddressUtils.sol
  packages/govern-contract-utils/contracts/erc165/ERC165.sol
  packages/govern-contract-utils/contracts/initializable/Initializable.sol
  packages/govern-contract-utils/contracts/minimal-proxies/ERC1167ProxyFactory.sol
  packages/govern-core/buidler.config.js
  packages/govern-core/contracts/Govern.sol
  packages/govern-core/contracts/pipelines/GovernQueue.sol
  packages/govern-core/test/govern.test.ts
  packages/govern-core/test/pipelines/govern-queue.test.ts
  packages/govern-create/buidler.config.js
  packages/govern-create/contracts/GovernBaseFactory.sol
  packages/govern-create/contracts/core-factories/GovernFactory.sol
  packages/govern-create/contracts/core-factories/GovernQueueFactory.sol
  packages/govern-create/lib/utils.js
  packages/govern-create/tasks/accounts.js
  packages/govern-create/tasks/deploy-factory.js
  packages/govern-create/tasks/deploy-govern.js
  packages/govern-create/tasks/deploy-registry.js
  packages/govern-create/test/base.js
  packages/govern-server/src/core/GovernCore.ts
  packages/govern-server/src/core/GraphqlClient.ts
  packages/govern-server/src/core/config.ts
  packages/govern-server/src/core/errors.ts
  packages/govern-server/src/core/params.ts
  packages/govern-server/src/core/types.ts
  packages/govern-server/src/core/utils/network.ts
  packages/govern-subgraph/manifest/data/rinkeby-staging.json
  packages/govern-subgraph/manifest/data/rinkeby.json
  packages/govern-subgraph/schema.graphql
  packages/govern-subgraph/src/GovernQueue.ts
  packages/govern-subgraph/subgraph.template.yaml
Labels: P0 🚒, S2: Bug 👩‍✈️, T0: Core 🌞

#86 Subgraph: rename to align with contracts
  .github/workflows/cd-rinkeby.yml
  packages/erc3k/contracts/ERC3000.sol
  packages/erc3k/contracts/ERC3000Data.sol
  packages/erc3k/contracts/test/ERC3000Mock.sol
  packages/govern-core/contracts/pipelines/GovernQueue.sol
  packages/govern-core/test/pipelines/govern-queue.test.ts
  packages/govern-create/contracts/GovernBaseFactory.sol
  packages/govern-create/contracts/core-factories/GovernQueueFactory.sol
  packages/govern-subgraph/manifest/data/rinkeby-staging.json
  packages/govern-subgraph/manifest/data/rinkeby.json
  packages/govern-subgraph/manifest/templates/contracts/ERC3000Registry.template.yaml
  packages/govern-subgraph/schema.graphql
  packages/govern-subgraph/src/ERC3000Registry.ts
  packages/govern-subgraph/src/Govern.ts
  packages/govern-subgraph/src/GovernQueue.ts
  packages/govern-subgraph/src/lib/MiniACL.ts
  packages/govern-subgraph/src/utils/constants.ts
  packages/govern-subgraph/src/utils/events.ts
  packages/govern-subgraph/src/utils/ids.ts
  packages/govern-subgraph/subgraph.template.yaml
Labels: P2 👀, S1: Feature 👨‍🎨, T2: DX 👷‍♀️

#104 Docs: boostrap
  docs/README.md
  docs/SUMMARY.md
  docs/assets/govern-logo.png
  docs/guides/getting-started.md
Labels: S6: Docs 👩‍💻

#132 Create, core: Allow to create token from GovernBaseFactory
  .github/workflows/cd-rinkeby.yml
  README.md
  docs/developers/historical-deployments.md
  packages/erc3k/contracts/IERC3000Registry.sol
  packages/erc3k/contracts/test/ERC3000DataLibTest.sol
  packages/erc3k/package.json
  packages/erc3k/test/erc3k-data.test.ts
  packages/govern-contract-utils/contracts/minimal-proxies/ERC1167ProxyFactory.sol
  packages/govern-core/contracts/GovernRegistry.sol
  packages/govern-core/test/govern-registry.test.ts
  packages/govern-create/contracts/GovernBaseFactory.sol
  packages/govern-create/package.json
  packages/govern-create/tasks/deploy-factory.js
  packages/govern-create/tasks/deploy-govern.js
  packages/govern-create/test/base.js
  packages/govern-subgraph/manifest/data/rinkeby-staging.json
  packages/govern-subgraph/manifest/data/rinkeby.json
  packages/govern-token/contracts/GovernTokenFactory.sol
Labels: P2 👀, S1: Feature 👨‍🎨, T2: DX 👷‍♀️

#77 Govern JS Client
  README.md
  docs/SUMMARY.md
  docs/developers/govern-js.md
  packages/govern/.gitignore
  packages/govern/README.md
  packages/govern/internal/actions/DaoAction.ts
  packages/govern/internal/actions/DaosAction.ts
  packages/govern/internal/actions/lib/AbstractAction.ts
  packages/govern/internal/clients/graphql/GraphQLClient.ts
  packages/govern/internal/clients/graphql/fragments/registry-entry.ts
  packages/govern/internal/clients/graphql/queries/dao.ts
  packages/govern/internal/clients/graphql/queries/daos.ts
  packages/govern/internal/clients/lib/ClientInterface.ts
  packages/govern/internal/clients/lib/types/Address.ts
  packages/govern/internal/configuration/Configuration.ts
  packages/govern/jest.config.js
  packages/govern/package.json
  packages/govern/public/configure.ts
  packages/govern/public/dao.ts
  packages/govern/public/daos.ts
  packages/govern/public/index.ts
  packages/govern/public/query.ts
  packages/govern/tests/internal/actions/DaoActionTest.ts
  packages/govern/tests/internal/actions/DaosActionTest.ts
  packages/govern/tests/internal/actions/lib/AbstractActionTest.ts
  packages/govern/tests/internal/clients/GraphQLClientTest.ts
  packages/govern/tests/internal/configuration/ConfigurationTest.ts
  packages/govern/tests/public/configurationTest.ts
  packages/govern/tests/public/daoTest.ts
  packages/govern/tests/public/daosTest.ts
  packages/govern/tests/public/queryTest.ts
  packages/govern/tsconfig.cjs.json
  packages/govern/tsconfig.esm.json
  packages/govern/tsconfig.json
  packages/govern/tslint.json
  yarn.lock
Labels: P2 👀, S1: Feature 👨‍🎨, T2: DX 👷‍♀️
